### ISSUE TITLE
TypeError: chrome.Options is not a constructor   

### ISSUE THREAD

**Issue by s7dhansh** [meteortesting/meteor-browser-tests#16]
This is the error I am getting on running `TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha --port 3100`

```
W20180804-11:17:41.234(5.5)? (STDERR) meteor://💻app/packages/meteortesting_browser-tests.js:144                                                                                                                           
W20180804-11:17:41.235(5.5)? (STDERR)   const options = new chrome.Options();                                                                                                                                              
W20180804-11:17:41.235(5.5)? (STDERR)                   ^                                                                                                                                                                  
W20180804-11:17:41.235(5.5)? (STDERR)                                                                                                                                                                                      
W20180804-11:17:41.236(5.5)? (STDERR) TypeError: chrome.Options is not a constructor                                                                                                                                       
W20180804-11:17:41.236(5.5)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:44:19)                                                                                              
W20180804-11:17:41.236(5.5)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)                                                                                                            
W20180804-11:17:41.236(5.5)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:138:3)                                                                                                                    
W20180804-11:17:41.237(5.5)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:168:7)                                                                                                                    
W20180804-11:17:41.237(5.5)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:118:13)                                           
```

Can someone help?
I used `meteor npm i --save-dev selenium@3 chromdriver`

**Comment by aldeed** [comment]
@s7dhansh You'll need to make a repo with an example app in it that shows this error happening. Otherwise there is not much we can do to debug this. Thanks.

**Comment by SimonSimCity** [comment]
Closed due to lack of feedback. If you see this happening again please tell us the exact version of `selenium` and `chromdriver` you've installed or create a repository where we can reproduce this.
