### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Floriferous** [meteortesting/meteor-browser-tests#23]
When running on circle CI with nightmare we're seeing the following error that crashes our client-side tests:

```sh
I20190820-16:20:47.578(0)? uncaughtException error TypeError: Cannot read property 'split' of undefined
I20190820-16:20:47.578(0)?     at EventEmitter.nightmare.on.on (packages/meteortesting:browser-tests/browser/nightmare.js:52:38)
I20190820-16:20:47.578(0)?     at emitOne (events.js:116:13)
I20190820-16:20:47.578(0)?     at EventEmitter.emit (events.js:211:7)
I20190820-16:20:47.578(0)?     at ChildProcess.<anonymous> (/home/circleci/app/microservices/www/node_modules/nightmare/lib/ipc.js:49:10)
I20190820-16:20:47.578(0)?     at emitTwo (events.js:126:13)
I20190820-16:20:47.578(0)?     at ChildProcess.emit (events.js:214:7)
I20190820-16:20:47.579(0)?     at emit (internal/child_process.js:762:12)
I20190820-16:20:47.579(0)?     at _combinedTickCallback (internal/process/next_tick.js:142:11)
I20190820-16:20:47.579(0)?     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

Any idea what might cause this?

**Comment by SimonSimCity** [comment]
Should be fixed by #24. Please re-open if it's still present.
